image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # Устанавливаем Gradle системно
  - apt-get install -y gradle
  # Запускаем приложение
  - java -jar ./artifacts/app-replan-delivery.jar &
  - sleep 15

build_script:
  # Используем системный gradle вместо wrapper
  - gradle test --info "-Dselenide.headless=true"